deployments:
  default:
    ready_wait: 120
    filename: ./stuff/Dockerfile
    context_path: ./stuff
    dockerfileonly: true
    depends_on:
      - PRODUCTS_API:
          app: child-deployment/[dev]
      
      
